# Generated by Django 6.0.1 on 2026-02-11 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='evidencia',
            field=models.TextField(default='', verbose_name='TIPO DE EVIDENCIA'),
            preserve_default=False,
        ),
    ]
