# Generated by Django 6.0.1 on 2026-02-11 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_proyecto_evidencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='evidencia',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='TIPO DE EVIDENCIA'),
        ),
    ]
