# Generated by Django 6.0.1 on 2026-02-11 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_proyecto_evidencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='dictamen',
            field=models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('APROBADO', 'APROBADO'), ('NO APROBADO', 'NO APROBADO')], default='PENDIENTE', max_length=50, verbose_name='DICTAMEN FINAL'),
        ),
    ]
