# Generated by Django 6.0.1 on 2026-02-11 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_proyecto_dictamen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='nivel_competencia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='MÓDULOS REGISTRADOS'),
        ),
    ]
