# Generated by Django 6.0.1 on 2026-01-21 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('codigo_estudiante', models.CharField(max_length=9, primary_key=True, serialize=False, verbose_name='CÓDIGO DE ESTUDIANTE')),
                ('nombre_completo', models.CharField(max_length=200, verbose_name='NOMBRE COMPLETO')),
                ('correo_electronico', models.EmailField(blank=True, max_length=100, null=True, verbose_name='CORREO ELECTRÓNICO')),
            ],
            options={
                'verbose_name': 'Alumno (Participante)',
                'verbose_name_plural': 'Alumnos (Participantes)',
            },
        ),
        migrations.CreateModel(
            name='Asesor',
            fields=[
                ('codigo_asesor', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='CÓDIGO DE ASESOR')),
                ('nombre_completo', models.CharField(max_length=200, verbose_name='NOMBRE COMPLETO')),
                ('correo_electronico', models.EmailField(max_length=254, verbose_name='CORREO ELECTRÓNICO')),
            ],
            options={
                'verbose_name': 'Asesor',
                'verbose_name_plural': 'Asesores',
            },
        ),
        migrations.CreateModel(
            name='Evaluador',
            fields=[
                ('codigo_evaluador', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='CÓDIGO DE EVALUADOR')),
                ('nombre_completo', models.CharField(max_length=200, verbose_name='NOMBRE COMPLETO')),
                ('correo_evaluador', models.EmailField(max_length=254, verbose_name='CORREO EVALUADOR')),
                ('especializacion', models.CharField(max_length=100, verbose_name='ESPECIALIZACIÓN')),
            ],
            options={
                'verbose_name': 'Evaluador',
                'verbose_name_plural': 'Evaluadores',
            },
        ),
    ]
